## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "k-Points" );
LoadPackage( "IO_ForHomalg" );
HOMALG_IO.show_banners := false;
HOMALG_IO.use_common_stream := true;
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "k-Points", "doc" )[1]![1], "k-Points.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "k-Points" );
QUIT;
